from .employees.employee_list import employee_list
from .computers.computer import computer_list
from .computers.details import computer_details
from .computers.form import *
from .home import home
from .auth.logout import logout_user
from .departments.department_list import department_list
from .connection import Connection
from .trainingprograms.training_program_list import training_program_list
